FROM ghcr.io/downunderctf/docker-vendor/nsjail:ubuntu-24.04

RUN pip install -t /lib/python3/dist-packages pycryptodome

ENV FLAG=skbdg{67_sick_savant_Sikhs_event_C._X._Evan_seeks_heaven_six_seven}

COPY ./67ot.py /home/ctf/chal/pwn